### ISSUE TITLE
git_prompt.sh  problem

### ISSUE THREAD

**Issue by boiseamit** [BoiseState/tools#1]
The git_prompt shows red status incorrectly. I am using git 2.9.3 on Fedora 25.  The commented line is correct for my case so I am assuming that different versions of git put a different message? May be combine the two conditions.

#if [[ ${git_status} =~ "working tree clean" ]]; then
  if [[ ${git_status} =~ "working directory clean" ]]; then

**Comment by shanep** [comment]
I will get a new regex that is not so strict

**Comment by shanep** [comment]
Fixing this will require a complete script update to move everything to --porcelain commands. So I am marking this as no fix for now.

**Comment by shanep** [comment]
Additionally, all these scripts were forked from github.com:shanep/os-config which are my personal config files. I don't have the bandwidth to maintain both. Either you need to point this repo to my personal config files or take over maintenance or just delete this repo entirely.

**Comment by boiseamit** [comment]
Hmm...I had no idea. I got this from the tools repo in the BoiseState, which seems to be maintained by yourself and Marissa. Do you mean to delete that repo?

**Comment by shanep** [comment]
Do you want to maintain this repo? If not then I am deleting it.

**Comment by boiseamit** [comment]
Yeah, this is just your repo. It should be removed. I can get stuff from your repo directly if I want. There is reference to it in 253 notes (GIT notes) so you should update those notes to point to your site or remove the reference. You  probably want to also inform Marissa as she has been using this as well?
